/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.a3;

import Classes.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Editarusu extends javax.swing.JFrame {

    /**
     * Creates new form Editarusu
     */
    public Editarusu() {
        initComponents();
    }
     public void abrirTelaMenu() {
        // Feche a tela de login
        dispose();

        // Crie e exiba a tela de menu
        NTelaMenu NTelaMenu = new NTelaMenu();
        NTelaMenu.setVisible(true);
    }
      public void abrirEditarEmp() {
        // Feche a tela de login
        dispose();

        // Crie e exiba a tela de menu
        EditarEmp ee = new EditarEmp();
        ee.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cksenha1 = new javax.swing.JCheckBox();
        txtsenhaconf3 = new javax.swing.JPasswordField();
        txtsenha3 = new javax.swing.JPasswordField();
        txtemailusu = new javax.swing.JTextField();
        txtcpfusu = new javax.swing.JTextField();
        txtnomeusu = new javax.swing.JTextField();
        txtlograusu = new javax.swing.JTextField();
        txtcomplusu = new javax.swing.JTextField();
        txtbairrousu = new javax.swing.JTextField();
        txtcidadeusu = new javax.swing.JTextField();
        txtcepusu = new javax.swing.JTextField();
        txtufusu = new javax.swing.JTextField();
        foto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cksenha1.setText("Mostrar senha");
        cksenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cksenha1ActionPerformed(evt);
            }
        });
        getContentPane().add(cksenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        txtsenhaconf3.setBackground(new java.awt.Color(246, 246, 233));
        txtsenhaconf3.setBorder(null);
        txtsenhaconf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaconf3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtsenhaconf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 393, 250, 20));

        txtsenha3.setBackground(new java.awt.Color(246, 246, 233));
        txtsenha3.setBorder(null);
        txtsenha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenha3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtsenha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 330, 250, 20));

        txtemailusu.setBackground(new java.awt.Color(246, 246, 233));
        txtemailusu.setBorder(null);
        getContentPane().add(txtemailusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 275, 260, 20));

        txtcpfusu.setBackground(new java.awt.Color(246, 246, 233));
        txtcpfusu.setBorder(null);
        txtcpfusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfusuActionPerformed(evt);
            }
        });
        getContentPane().add(txtcpfusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 218, 260, 20));

        txtnomeusu.setBackground(new java.awt.Color(246, 246, 233));
        txtnomeusu.setBorder(null);
        getContentPane().add(txtnomeusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 260, 20));

        txtlograusu.setBackground(new java.awt.Color(246, 246, 233));
        txtlograusu.setBorder(null);
        getContentPane().add(txtlograusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 160, 260, 20));

        txtcomplusu.setBackground(new java.awt.Color(246, 246, 233));
        txtcomplusu.setBorder(null);
        txtcomplusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcomplusuActionPerformed(evt);
            }
        });
        getContentPane().add(txtcomplusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 220, 260, 20));

        txtbairrousu.setBackground(new java.awt.Color(246, 246, 233));
        txtbairrousu.setBorder(null);
        getContentPane().add(txtbairrousu, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 278, 260, 20));

        txtcidadeusu.setBackground(new java.awt.Color(246, 246, 233));
        txtcidadeusu.setBorder(null);
        getContentPane().add(txtcidadeusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 330, 160, 20));

        txtcepusu.setBackground(new java.awt.Color(246, 246, 233));
        txtcepusu.setBorder(null);
        getContentPane().add(txtcepusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 393, 250, 20));

        txtufusu.setBackground(new java.awt.Color(246, 246, 233));
        txtufusu.setBorder(null);
        getContentPane().add(txtufusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 330, 70, 20));

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editardadosusu.png"))); // NOI18N
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 463, 250, 40));

        jButton4.setText("jButton2");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 40));

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 50, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtsenhaconf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaconf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaconf3ActionPerformed

    private void txtsenha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenha3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenha3ActionPerformed

    private void txtcpfusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfusuActionPerformed

    private void txtcomplusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcomplusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomplusuActionPerformed

    private void cksenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cksenha1ActionPerformed
        if (cksenha1.isSelected()) {
            txtsenha3.setEchoChar((char) 0);
            txtsenhaconf3.setEchoChar((char) 0);// Exibe a senha
        } else {
            txtsenha3.setEchoChar('*'); // Oculta a senha
            txtsenhaconf3.setEchoChar('*');
        }
    }//GEN-LAST:event_cksenha1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              
      Usuario usu = new Usuario();
      usu.setNome(txtnomeusu.getText());
      usu.setEmail(txtemailusu.getText());
      usu.setCpf(txtcpfusu.getText());
      usu.setSenha(txtsenha3.getText());
      usu.setLogradouro(txtlograusu.getText());
      usu.setComplementos(txtcomplusu.getText());
      usu.setBairro(txtbairrousu.getText());
      usu.setUf(txtufusu.getText());
      usu.setCidade(txtcidadeusu.getText());
      usu.setCep(txtcepusu.getText());
      
      usu.atualizar();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        abrirTelaMenu();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       abrirEditarEmp();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editarusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editarusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editarusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editarusu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editarusu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cksenha1;
    private javax.swing.JLabel foto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField txtbairrousu;
    private javax.swing.JTextField txtcepusu;
    private javax.swing.JTextField txtcidadeusu;
    private javax.swing.JTextField txtcomplusu;
    private javax.swing.JTextField txtcpfusu;
    private javax.swing.JTextField txtemailusu;
    private javax.swing.JTextField txtlograusu;
    private javax.swing.JTextField txtnomeusu;
    private javax.swing.JPasswordField txtsenha3;
    private javax.swing.JPasswordField txtsenhaconf3;
    private javax.swing.JTextField txtufusu;
    // End of variables declaration//GEN-END:variables
}
