/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.a3;

import Classes.Empresas;

/**
 *
 * @author User
 */
public class EditarEmp extends javax.swing.JFrame {

    /**
     * Creates new form EditarEmp
     */
    public EditarEmp() {
        initComponents();
    }
     public void abrirTelaMenu() {
        // Feche a tela de login
        dispose();

        // Crie e exiba a tela de menu
        NTelaMenu NTelaMenu = new NTelaMenu();
        NTelaMenu.setVisible(true);
    }
     public void abrirEditarUsu() {
        // Feche a tela de login
        dispose();

        // Crie e exiba a tela de menu
        Editarusu ee = new Editarusu();
        ee.setVisible(true);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtrazaoemp = new javax.swing.JTextField();
        txtcnpjemp = new javax.swing.JTextField();
        txtemailemp = new javax.swing.JTextField();
        txtsenha3 = new javax.swing.JPasswordField();
        txtsenhaconf3 = new javax.swing.JPasswordField();
        txtcepemp = new javax.swing.JTextField();
        txtufemp = new javax.swing.JTextField();
        txtcidadeemp = new javax.swing.JTextField();
        txtbairroemp = new javax.swing.JTextField();
        txtcomplemp = new javax.swing.JTextField();
        txtlograemp = new javax.swing.JTextField();
        cksenha1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtrazaoemp.setBackground(new java.awt.Color(246, 246, 233));
        txtrazaoemp.setBorder(null);
        getContentPane().add(txtrazaoemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 260, 20));

        txtcnpjemp.setBackground(new java.awt.Color(246, 246, 233));
        txtcnpjemp.setBorder(null);
        txtcnpjemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnpjempActionPerformed(evt);
            }
        });
        getContentPane().add(txtcnpjemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 218, 260, 20));

        txtemailemp.setBackground(new java.awt.Color(246, 246, 233));
        txtemailemp.setBorder(null);
        getContentPane().add(txtemailemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 278, 260, 20));

        txtsenha3.setBackground(new java.awt.Color(246, 246, 233));
        txtsenha3.setBorder(null);
        txtsenha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenha3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtsenha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 330, 250, 20));

        txtsenhaconf3.setBackground(new java.awt.Color(246, 246, 233));
        txtsenhaconf3.setBorder(null);
        txtsenhaconf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaconf3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtsenhaconf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 393, 250, 20));

        txtcepemp.setBackground(new java.awt.Color(246, 246, 233));
        txtcepemp.setBorder(null);
        getContentPane().add(txtcepemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 393, 250, 20));

        txtufemp.setBackground(new java.awt.Color(246, 246, 233));
        txtufemp.setBorder(null);
        getContentPane().add(txtufemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 330, 70, 20));

        txtcidadeemp.setBackground(new java.awt.Color(246, 246, 233));
        txtcidadeemp.setBorder(null);
        getContentPane().add(txtcidadeemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 330, 160, 20));

        txtbairroemp.setBackground(new java.awt.Color(246, 246, 233));
        txtbairroemp.setBorder(null);
        getContentPane().add(txtbairroemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 278, 260, 20));

        txtcomplemp.setBackground(new java.awt.Color(246, 246, 233));
        txtcomplemp.setBorder(null);
        txtcomplemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcomplempActionPerformed(evt);
            }
        });
        getContentPane().add(txtcomplemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 220, 260, 20));

        txtlograemp.setBackground(new java.awt.Color(246, 246, 233));
        txtlograemp.setBorder(null);
        getContentPane().add(txtlograemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 160, 260, 20));

        cksenha1.setText("Mostrar senha");
        cksenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cksenha1ActionPerformed(evt);
            }
        });
        getContentPane().add(cksenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editardadosempresa.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 463, 250, 40));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 40));

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 50, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcnpjempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnpjempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnpjempActionPerformed

    private void txtsenha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenha3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenha3ActionPerformed

    private void txtsenhaconf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaconf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaconf3ActionPerformed

    private void txtcomplempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcomplempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomplempActionPerformed

    private void cksenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cksenha1ActionPerformed
        if (cksenha1.isSelected()) {
            txtsenha3.setEchoChar((char) 0);
            txtsenhaconf3.setEchoChar((char) 0);// Exibe a senha
        } else {
            txtsenha3.setEchoChar('*'); // Oculta a senha
            txtsenhaconf3.setEchoChar('*');
        }
    }//GEN-LAST:event_cksenha1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Empresas usu = new Empresas();
        usu.setRazaosocial(txtrazaoemp.getText());
        usu.setEmail(txtemailemp.getText());
        usu.setCnpj(txtcnpjemp.getText());
        usu.setSenha(txtsenha3.getText());
        usu.setLogradouro(txtlograemp.getText());
        usu.setComplementos(txtcomplemp.getText());
        usu.setBairro(txtbairroemp.getText());
        usu.setUf(txtufemp.getText());
        usu.setCidade(txtcidadeemp.getText());
        usu.setCep(txtcepemp.getText());

        usu.atualizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        abrirTelaMenu();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        abrirEditarUsu();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cksenha1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtbairroemp;
    private javax.swing.JTextField txtcepemp;
    private javax.swing.JTextField txtcidadeemp;
    private javax.swing.JTextField txtcnpjemp;
    private javax.swing.JTextField txtcomplemp;
    private javax.swing.JTextField txtemailemp;
    private javax.swing.JTextField txtlograemp;
    private javax.swing.JTextField txtrazaoemp;
    private javax.swing.JPasswordField txtsenha3;
    private javax.swing.JPasswordField txtsenhaconf3;
    private javax.swing.JTextField txtufemp;
    // End of variables declaration//GEN-END:variables
}
