/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.a3;

import Classes.Empresas;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaCadEmp extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadEmp
     */
    public TelaCadEmp() {
        initComponents();
    }
    public void abrirTelalogin() {
        // Feche a tela de registro
        dispose();

        // Crie e exiba a tela de menu
        Telalogin telalogin = new Telalogin();
        telalogin.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cksenha = new javax.swing.JCheckBox();
        ckAdmin = new javax.swing.JCheckBox();
        txtsenhaconf = new javax.swing.JPasswordField();
        txtsenha = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        txtsenhaconf2 = new javax.swing.JPasswordField();
        txtsenha2 = new javax.swing.JPasswordField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        cksenha1 = new javax.swing.JCheckBox();
        ckAdmin1 = new javax.swing.JCheckBox();
        txtbairroemp = new javax.swing.JTextField();
        txtcomplemp = new javax.swing.JTextField();
        txtlograemp = new javax.swing.JTextField();
        txtsenhaconf3 = new javax.swing.JPasswordField();
        txtsenha3 = new javax.swing.JPasswordField();
        txtemailemp = new javax.swing.JTextField();
        txtcnpjemp = new javax.swing.JTextField();
        txtrazaoemp = new javax.swing.JTextField();
        txtcepemp = new javax.swing.JTextField();
        txtufemp = new javax.swing.JTextField();
        txtcidadeemp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btRegistrar = new javax.swing.JButton();
        btjatemconta = new javax.swing.JButton();

        cksenha.setText("Mostrar senha");
        cksenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cksenhaActionPerformed(evt);
            }
        });

        ckAdmin.setText("Admin");

        txtsenhaconf.setBackground(new java.awt.Color(246, 246, 233));
        txtsenhaconf.setBorder(null);

        txtsenha.setBackground(new java.awt.Color(246, 246, 233));
        txtsenha.setBorder(null);

        jTextField3.setBackground(new java.awt.Color(246, 246, 233));
        jTextField3.setBorder(null);

        jTextField2.setBackground(new java.awt.Color(246, 246, 233));
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(246, 246, 233));
        jTextField1.setBorder(null);

        txtsenhaconf2.setBackground(new java.awt.Color(246, 246, 233));
        txtsenhaconf2.setBorder(null);

        txtsenha2.setBackground(new java.awt.Color(246, 246, 233));
        txtsenha2.setBorder(null);

        jTextField7.setBackground(new java.awt.Color(246, 246, 233));
        jTextField7.setBorder(null);

        jTextField8.setBackground(new java.awt.Color(246, 246, 233));
        jTextField8.setBorder(null);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setBackground(new java.awt.Color(246, 246, 233));
        jTextField9.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cksenha1.setText("Mostrar senha");
        cksenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cksenha1ActionPerformed(evt);
            }
        });
        getContentPane().add(cksenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        ckAdmin1.setText("Admin");
        getContentPane().add(ckAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        txtbairroemp.setBackground(new java.awt.Color(246, 246, 233));
        txtbairroemp.setBorder(null);
        getContentPane().add(txtbairroemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 260, 20));

        txtcomplemp.setBackground(new java.awt.Color(246, 246, 233));
        txtcomplemp.setBorder(null);
        txtcomplemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcomplempActionPerformed(evt);
            }
        });
        getContentPane().add(txtcomplemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 205, 260, 20));

        txtlograemp.setBackground(new java.awt.Color(246, 246, 233));
        txtlograemp.setBorder(null);
        getContentPane().add(txtlograemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 260, 20));

        txtsenhaconf3.setBackground(new java.awt.Color(246, 246, 233));
        txtsenhaconf3.setBorder(null);
        txtsenhaconf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaconf3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtsenhaconf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 367, 250, 20));

        txtsenha3.setBackground(new java.awt.Color(246, 246, 233));
        txtsenha3.setBorder(null);
        txtsenha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenha3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtsenha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 250, 20));

        txtemailemp.setBackground(new java.awt.Color(246, 246, 233));
        txtemailemp.setBorder(null);
        getContentPane().add(txtemailemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 260, 20));

        txtcnpjemp.setBackground(new java.awt.Color(246, 246, 233));
        txtcnpjemp.setBorder(null);
        txtcnpjemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnpjempActionPerformed(evt);
            }
        });
        getContentPane().add(txtcnpjemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 205, 260, 20));

        txtrazaoemp.setBackground(new java.awt.Color(246, 246, 233));
        txtrazaoemp.setBorder(null);
        getContentPane().add(txtrazaoemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 260, 20));

        txtcepemp.setBackground(new java.awt.Color(246, 246, 233));
        txtcepemp.setBorder(null);
        getContentPane().add(txtcepemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 368, 250, 20));

        txtufemp.setBackground(new java.awt.Color(246, 246, 233));
        txtufemp.setBorder(null);
        getContentPane().add(txtufemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 70, 20));

        txtcidadeemp.setBackground(new java.awt.Color(246, 246, 233));
        txtcidadeemp.setBorder(null);
        getContentPane().add(txtcidadeemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 308, 160, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cadusunovo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btRegistrar.setText("jButton1");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 250, 30));

        btjatemconta.setText("jButton2");
        btjatemconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btjatemcontaActionPerformed(evt);
            }
        });
        getContentPane().add(btjatemconta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 476, 40, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cksenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cksenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cksenhaActionPerformed

    private void cksenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cksenha1ActionPerformed
       if (cksenha1.isSelected()) {
            txtsenha3.setEchoChar((char) 0);
            txtsenhaconf3.setEchoChar((char) 0);// Exibe a senha
        } else {
            txtsenha3.setEchoChar('*'); // Oculta a senha
             txtsenhaconf3.setEchoChar('*');
        }
    }//GEN-LAST:event_cksenha1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void txtcomplempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcomplempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomplempActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void txtcnpjempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnpjempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnpjempActionPerformed

    private void txtsenha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenha3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenha3ActionPerformed

    private void txtsenhaconf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaconf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaconf3ActionPerformed

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        Empresas emp = new Empresas();
       String senha, confsenha;
       
       senha = txtsenha3.getText();
       confsenha = txtsenhaconf3.getText();
       
        
        if (senha == null ? confsenha == null : senha.equals(confsenha)) {
         emp.setRazaosocial(txtrazaoemp.getText());
      emp.setEmail(txtemailemp.getText());
      emp.setCnpj(txtcnpjemp.getText());
      emp.setSenha(txtsenha3.getText());
      emp.setLogradouro(txtlograemp.getText());
      emp.setComplementos(txtcomplemp.getText());
      emp.setBairro(txtbairroemp.getText());
      emp.setUf(txtufemp.getText());
      emp.setCidade(txtcidadeemp.getText());
      emp.setCep(txtcepemp.getText());
      emp.Inserir(); }
        else {
            JOptionPane.showMessageDialog(null, "Senhas incompativeis");
        }
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void btjatemcontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btjatemcontaActionPerformed
        abrirTelalogin();
    }//GEN-LAST:event_btjatemcontaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton btjatemconta;
    private javax.swing.JCheckBox ckAdmin;
    private javax.swing.JCheckBox ckAdmin1;
    private javax.swing.JCheckBox cksenha;
    private javax.swing.JCheckBox cksenha1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txtbairroemp;
    private javax.swing.JTextField txtcepemp;
    private javax.swing.JTextField txtcidadeemp;
    private javax.swing.JTextField txtcnpjemp;
    private javax.swing.JTextField txtcomplemp;
    private javax.swing.JTextField txtemailemp;
    private javax.swing.JTextField txtlograemp;
    private javax.swing.JTextField txtrazaoemp;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JPasswordField txtsenha2;
    private javax.swing.JPasswordField txtsenha3;
    private javax.swing.JPasswordField txtsenhaconf;
    private javax.swing.JPasswordField txtsenhaconf2;
    private javax.swing.JPasswordField txtsenhaconf3;
    private javax.swing.JTextField txtufemp;
    // End of variables declaration//GEN-END:variables
}
