/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.a3;

import Classes.Empresas;
import Classes.Usuario;
import DAO.ConnectionFactory;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class TelaloginEMp extends javax.swing.JFrame {

    /**
     * Creates new form TelaloginEMp
     */
    public TelaloginEMp() {
        initComponents();
    }
     public void abrirNTelaMenu() {
        // Feche a tela de login
        dispose();

        // Crie e exiba a tela de menu
        NTelaMenu NTelaMenu = new NTelaMenu();
        NTelaMenu.setVisible(true);
    }
    
     public void abrirTelaCadUsu() {
        // Feche a tela de login
        dispose();

        // Crie e exiba a tela de menu
        UACadUsu TCU = new UACadUsu();
        TCU.setVisible(true);
     }
     
     public void abrirTelalogin() {
        // Feche a tela de registro
        dispose();

        // Crie e exiba a tela de menu
        Telalogin telalogin = new Telalogin();
        telalogin.setVisible(true);
     }
     public void abrirTelaediçãoEmp(){
         dispose();
         
         EditarEmp edu = new EditarEmp();
         edu.setVisible(true);
     
     }
      public void abrirTelaLoginUsu(){
         dispose();
         
         Telalogin tl = new Telalogin();
         tl.setVisible(true);
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btregistrar = new javax.swing.JButton();
        btlogar = new javax.swing.JButton();
        txtemplogin = new javax.swing.JTextField();
        txtsenhalogin = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CECENIPEJOTA.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btregistrar.setText("jButton1");
        btregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 100, -1));

        btlogar.setText("jButton2");
        btlogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlogarActionPerformed(evt);
            }
        });
        getContentPane().add(btlogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 403, 280, 30));

        txtemplogin.setBackground(new java.awt.Color(240, 245, 241));
        txtemplogin.setBorder(null);
        txtemplogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemploginActionPerformed(evt);
            }
        });
        getContentPane().add(txtemplogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 256, 250, 30));

        txtsenhalogin.setBackground(new java.awt.Color(240, 245, 241));
        txtsenhalogin.setBorder(null);
        getContentPane().add(txtsenhalogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 336, 250, 30));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 50));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 140, 20));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 473, 150, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btregistrarActionPerformed
        abrirTelaCadUsu();
    }//GEN-LAST:event_btregistrarActionPerformed

    private void btlogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlogarActionPerformed
        //pega o login do usuário
        String Cnpj = txtemplogin.getText();
        //pega a senha do usuário como char[] e converte para String
        String Senha = new String (txtsenhalogin.getPassword());

        //verifica se o usuário é válido
        Empresas usu = new Empresas (Cnpj, Senha);
        boolean empExiste = false;
        try {
            empExiste = usu.login();
        } catch (SQLException ex) {
            Logger.getLogger(Telalogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (empExiste){
            JOptionPane.showMessageDialog(null, "Bem vindo, " + usu.getRazaosocial());
            dispose ();

            abrirNTelaMenu();}
        else
        JOptionPane.showMessageDialog(null, "Login invalido");

    }//GEN-LAST:event_btlogarActionPerformed

    private void txtemploginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemploginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemploginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           abrirNTelaMenu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        abrirTelaediçãoEmp();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        abrirTelaLoginUsu();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaloginEMp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaloginEMp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaloginEMp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaloginEMp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaloginEMp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btlogar;
    private javax.swing.JButton btregistrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtemplogin;
    private javax.swing.JPasswordField txtsenhalogin;
    // End of variables declaration//GEN-END:variables
}
