/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.a3;

import Classes.Usuario;

/**
 *
 * @author User
 */
public class TelaCadUsu extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadUsu
     */
    public TelaCadUsu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtconfsenhausu = new javax.swing.JPasswordField();
        txtsenhausu = new javax.swing.JPasswordField();
        cksenha = new javax.swing.JCheckBox();
        ckAdmin = new javax.swing.JCheckBox();
        txtnomeusu = new javax.swing.JTextField();
        txtcpfusu = new javax.swing.JTextField();
        txtemailusu = new javax.swing.JTextField();
        txtcidadeusu = new javax.swing.JTextField();
        txtcomplusu = new javax.swing.JTextField();
        txtlograusu = new javax.swing.JTextField();
        txtbairrousu = new javax.swing.JTextField();
        txtcepusu = new javax.swing.JTextField();
        txtufusu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btRegistrar = new javax.swing.JButton();
        btjatemconta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtconfsenhausu.setBackground(new java.awt.Color(246, 246, 233));
        txtconfsenhausu.setBorder(null);
        getContentPane().add(txtconfsenhausu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 365, 250, 20));

        txtsenhausu.setBackground(new java.awt.Color(246, 246, 233));
        txtsenhausu.setBorder(null);
        getContentPane().add(txtsenhausu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 308, 250, 20));

        cksenha.setText("Mostrar senha");
        cksenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cksenhaActionPerformed(evt);
            }
        });
        getContentPane().add(cksenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        ckAdmin.setText("Admin");
        getContentPane().add(ckAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        txtnomeusu.setBackground(new java.awt.Color(246, 246, 233));
        txtnomeusu.setBorder(null);
        txtnomeusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeusuActionPerformed(evt);
            }
        });
        getContentPane().add(txtnomeusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 260, 20));

        txtcpfusu.setBackground(new java.awt.Color(246, 246, 233));
        txtcpfusu.setBorder(null);
        txtcpfusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfusuActionPerformed(evt);
            }
        });
        getContentPane().add(txtcpfusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 203, 260, 20));

        txtemailusu.setBackground(new java.awt.Color(246, 246, 233));
        txtemailusu.setBorder(null);
        getContentPane().add(txtemailusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 256, 260, 20));

        txtcidadeusu.setBackground(new java.awt.Color(246, 246, 233));
        txtcidadeusu.setBorder(null);
        getContentPane().add(txtcidadeusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 308, 160, 20));

        txtcomplusu.setBackground(new java.awt.Color(246, 246, 233));
        txtcomplusu.setBorder(null);
        txtcomplusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcomplusuActionPerformed(evt);
            }
        });
        getContentPane().add(txtcomplusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 205, 260, 20));

        txtlograusu.setBackground(new java.awt.Color(246, 246, 233));
        txtlograusu.setBorder(null);
        getContentPane().add(txtlograusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 260, 20));

        txtbairrousu.setBackground(new java.awt.Color(246, 246, 233));
        txtbairrousu.setBorder(null);
        getContentPane().add(txtbairrousu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 258, 260, 20));

        txtcepusu.setBackground(new java.awt.Color(246, 246, 233));
        txtcepusu.setBorder(null);
        getContentPane().add(txtcepusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 368, 250, 20));

        txtufusu.setBackground(new java.awt.Color(246, 246, 233));
        txtufusu.setBorder(null);
        getContentPane().add(txtufusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 70, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Caddefinitivo(euacho).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 900, 600));

        btRegistrar.setText("jButton1");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 250, 30));

        btjatemconta.setText("jButton2");
        btjatemconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btjatemcontaActionPerformed(evt);
            }
        });
        getContentPane().add(btjatemconta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 476, 40, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

      public void abrirTelalogin() {
        // Feche a tela de registro
        dispose();

        // Crie e exiba a tela de menu
        Telalogin telalogin = new Telalogin();
        telalogin.setVisible(true);
     }
    private void cksenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cksenhaActionPerformed
       if (cksenha.isSelected()) {
            txtsenhausu.setEchoChar((char) 0);
            txtconfsenhausu.setEchoChar((char) 0);// Exibe a senha
        } else {
            txtsenhausu.setEchoChar('*'); // Oculta a senha
             txtconfsenhausu.setEchoChar('*');
        }
    }//GEN-LAST:event_cksenhaActionPerformed

    private void txtcpfusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfusuActionPerformed

    private void btjatemcontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btjatemcontaActionPerformed
    abrirTelalogin();
    }//GEN-LAST:event_btjatemcontaActionPerformed

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
      Usuario usu = new Usuario();
      usu.setNome(txtnomeusu.getText());
      usu.setEmail(txtemailusu.getText());
      usu.setCpf(txtcpfusu.getText());
      usu.setSenha(txtsenhausu.getText());
      usu.setLogradouro(txtlograusu.getText());
      usu.setComplementos(txtcomplusu.getText());
      usu.setBairro(txtbairrousu.getText());
      usu.setUf(txtufusu.getText());
      usu.setCidade(txtcidadeusu.getText());
      usu.setCep(txtcepusu.getText());
      
      usu.Inserir();
      
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void txtcomplusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcomplusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomplusuActionPerformed

    private void txtnomeusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeusuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeusuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadUsu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton btjatemconta;
    private javax.swing.JCheckBox ckAdmin;
    private javax.swing.JCheckBox cksenha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtbairrousu;
    private javax.swing.JTextField txtcepusu;
    private javax.swing.JTextField txtcidadeusu;
    private javax.swing.JTextField txtcomplusu;
    private javax.swing.JPasswordField txtconfsenhausu;
    private javax.swing.JTextField txtcpfusu;
    private javax.swing.JTextField txtemailusu;
    private javax.swing.JTextField txtlograusu;
    private javax.swing.JTextField txtnomeusu;
    private javax.swing.JPasswordField txtsenhausu;
    private javax.swing.JTextField txtufusu;
    // End of variables declaration//GEN-END:variables
}
